/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * Forbidden model
 * @param error Forbidden message
 * @param ssoStatus status code received from SSO
 */

data class Forbidden (
    /* Forbidden message */
    @Json(name = "error")
    var error: kotlin.String,
    /* status code received from SSO */
    @Json(name = "sso_status")
    var ssoStatus: kotlin.Int? = null
)

