/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdMailLabelsLabel

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param labels labels array
 * @param totalUnreadCount total_unread_count integer
 */

data class GetCharactersCharacterIdMailLabelsOk (
    /* labels array */
    @Json(name = "labels")
    var labels: kotlin.Array<GetCharactersCharacterIdMailLabelsLabel>? = null,
    /* total_unread_count integer */
    @Json(name = "total_unread_count")
    var totalUnreadCount: kotlin.Int? = null
)

