/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param message message string
 * @param notificationId notification_id integer
 * @param sendDate send_date string
 * @param senderCharacterId sender_character_id integer
 * @param standingLevel A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent
 */

data class GetCharactersCharacterIdNotificationsContacts200Ok (
    /* message string */
    @Json(name = "message")
    var message: kotlin.String,
    /* notification_id integer */
    @Json(name = "notification_id")
    var notificationId: kotlin.Int,
    /* send_date string */
    @Json(name = "send_date")
    var sendDate: java.time.OffsetDateTime,
    /* sender_character_id integer */
    @Json(name = "sender_character_id")
    var senderCharacterId: kotlin.Int,
    /* A number representing the standing level the receiver has been added at by the sender. The standing levels are as follows: -10 -> Terrible | -5 -> Bad |  0 -> Neutral |  5 -> Good |  10 -> Excellent */
    @Json(name = "standing_level")
    var standingLevel: kotlin.Float
)

