/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param agentId agent_id integer
 * @param pointsPerDay points_per_day number
 * @param remainderPoints remainder_points number
 * @param skillTypeId skill_type_id integer
 * @param startedAt started_at string
 */

data class GetCharactersCharacterIdAgentsResearch200Ok (
    /* agent_id integer */
    @Json(name = "agent_id")
    var agentId: kotlin.Int,
    /* points_per_day number */
    @Json(name = "points_per_day")
    var pointsPerDay: kotlin.Float,
    /* remainder_points number */
    @Json(name = "remainder_points")
    var remainderPoints: kotlin.Float,
    /* skill_type_id integer */
    @Json(name = "skill_type_id")
    var skillTypeId: kotlin.Int,
    /* started_at string */
    @Json(name = "started_at")
    var startedAt: java.time.OffsetDateTime
)

