/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param shipItemId Item id's are unique to a ship and persist until it is repackaged. This value can be used to track repeated uses of a ship, or detect when a pilot changes into a different instance of the same ship type.
 * @param shipName ship_name string
 * @param shipTypeId ship_type_id integer
 */

data class GetCharactersCharacterIdShipOk (
    /* Item id's are unique to a ship and persist until it is repackaged. This value can be used to track repeated uses of a ship, or detect when a pilot changes into a different instance of the same ship type. */
    @Json(name = "ship_item_id")
    var shipItemId: kotlin.Long,
    /* ship_name string */
    @Json(name = "ship_name")
    var shipName: kotlin.String,
    /* ship_type_id integer */
    @Json(name = "ship_type_id")
    var shipTypeId: kotlin.Int
)

