/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param shareCount share_count integer
 * @param shareholderId shareholder_id integer
 * @param shareholderType shareholder_type string
 */

data class GetCorporationsCorporationIdShareholders200Ok (
    /* share_count integer */
    @Json(name = "share_count")
    var shareCount: kotlin.Long,
    /* shareholder_id integer */
    @Json(name = "shareholder_id")
    var shareholderId: kotlin.Int,
    /* shareholder_type string */
    @Json(name = "shareholder_type")
    var shareholderType: GetCorporationsCorporationIdShareholders200Ok.ShareholderType
) {

    /**
    * shareholder_type string
    * Values: character,corporation
    */
    
    enum class ShareholderType(val value: kotlin.String){
        @Json(name = "character") character("character"),
        @Json(name = "corporation") corporation("corporation");
    }
}

