/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * graphic object
 * @param color color integer
 * @param graphic graphic string
 * @param layer layer integer
 * @param part part integer
 */

data class GetCharactersCharacterIdMedalsGraphic (
    /* color integer */
    @Json(name = "color")
    var color: kotlin.Int? = null,
    /* graphic string */
    @Json(name = "graphic")
    var graphic: kotlin.String,
    /* layer integer */
    @Json(name = "layer")
    var layer: kotlin.Int,
    /* part integer */
    @Json(name = "part")
    var part: kotlin.Int
)

