/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param chunkArrivalTime The time at which the chunk being extracted will arrive and can be fractured by the moon mining drill. 
 * @param extractionStartTime The time at which the current extraction was initiated. 
 * @param moonId moon_id integer
 * @param naturalDecayTime The time at which the chunk being extracted will naturally fracture if it is not first fractured by the moon mining drill. 
 * @param structureId structure_id integer
 */

data class GetCorporationCorporationIdMiningExtractions200Ok (
    /* The time at which the chunk being extracted will arrive and can be fractured by the moon mining drill.  */
    @Json(name = "chunk_arrival_time")
    var chunkArrivalTime: java.time.OffsetDateTime,
    /* The time at which the current extraction was initiated.  */
    @Json(name = "extraction_start_time")
    var extractionStartTime: java.time.OffsetDateTime,
    /* moon_id integer */
    @Json(name = "moon_id")
    var moonId: kotlin.Int,
    /* The time at which the chunk being extracted will naturally fracture if it is not first fractured by the moon mining drill.  */
    @Json(name = "natural_decay_time")
    var naturalDecayTime: java.time.OffsetDateTime,
    /* structure_id integer */
    @Json(name = "structure_id")
    var structureId: kotlin.Long
)

