/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param lastUpdate last_update string
 * @param numPins num_pins integer
 * @param ownerId owner_id integer
 * @param planetId planet_id integer
 * @param planetType planet_type string
 * @param solarSystemId solar_system_id integer
 * @param upgradeLevel upgrade_level integer
 */

data class GetCharactersCharacterIdPlanets200Ok (
    /* last_update string */
    @Json(name = "last_update")
    var lastUpdate: java.time.OffsetDateTime,
    /* num_pins integer */
    @Json(name = "num_pins")
    var numPins: kotlin.Int,
    /* owner_id integer */
    @Json(name = "owner_id")
    var ownerId: kotlin.Int,
    /* planet_id integer */
    @Json(name = "planet_id")
    var planetId: kotlin.Int,
    /* planet_type string */
    @Json(name = "planet_type")
    var planetType: GetCharactersCharacterIdPlanets200Ok.PlanetType,
    /* solar_system_id integer */
    @Json(name = "solar_system_id")
    var solarSystemId: kotlin.Int,
    /* upgrade_level integer */
    @Json(name = "upgrade_level")
    var upgradeLevel: kotlin.Int
) {

    /**
    * planet_type string
    * Values: temperate,barren,oceanic,ice,gas,lava,storm,plasma
    */
    
    enum class PlanetType(val value: kotlin.String){
        @Json(name = "temperate") temperate("temperate"),
        @Json(name = "barren") barren("barren"),
        @Json(name = "oceanic") oceanic("oceanic"),
        @Json(name = "ice") ice("ice"),
        @Json(name = "gas") gas("gas"),
        @Json(name = "lava") lava("lava"),
        @Json(name = "storm") storm("storm"),
        @Json(name = "plasma") plasma("plasma");
    }
}

