/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param isBlueprintCopy is_blueprint_copy boolean
 * @param isIncluded true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract
 * @param itemId Unique ID for the item being sold. Not present if item is being requested by contract rather than sold with contract
 * @param materialEfficiency Material Efficiency Level of the blueprint
 * @param quantity Number of items in the stack
 * @param recordId Unique ID for the item, used by the contract system
 * @param runs Number of runs remaining if the blueprint is a copy, -1 if it is an original
 * @param timeEfficiency Time Efficiency Level of the blueprint
 * @param typeId Type ID for item
 */

data class GetContractsPublicItemsContractId200Ok (
    /* is_blueprint_copy boolean */
    @Json(name = "is_blueprint_copy")
    var isBlueprintCopy: kotlin.Boolean? = null,
    /* true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract */
    @Json(name = "is_included")
    var isIncluded: kotlin.Boolean,
    /* Unique ID for the item being sold. Not present if item is being requested by contract rather than sold with contract */
    @Json(name = "item_id")
    var itemId: kotlin.Long? = null,
    /* Material Efficiency Level of the blueprint */
    @Json(name = "material_efficiency")
    var materialEfficiency: kotlin.Int? = null,
    /* Number of items in the stack */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* Unique ID for the item, used by the contract system */
    @Json(name = "record_id")
    var recordId: kotlin.Long,
    /* Number of runs remaining if the blueprint is a copy, -1 if it is an original */
    @Json(name = "runs")
    var runs: kotlin.Int? = null,
    /* Time Efficiency Level of the blueprint */
    @Json(name = "time_efficiency")
    var timeEfficiency: kotlin.Int? = null,
    /* Type ID for item */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

