/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param createdAt created_at string
 * @param creatorId ID of the character who created this medal
 * @param description description string
 * @param medalId medal_id integer
 * @param title title string
 */

data class GetCorporationsCorporationIdMedals200Ok (
    /* created_at string */
    @Json(name = "created_at")
    var createdAt: java.time.OffsetDateTime,
    /* ID of the character who created this medal */
    @Json(name = "creator_id")
    var creatorId: kotlin.Int,
    /* description string */
    @Json(name = "description")
    var description: kotlin.String,
    /* medal_id integer */
    @Json(name = "medal_id")
    var medalId: kotlin.Int,
    /* title string */
    @Json(name = "title")
    var title: kotlin.String
)

