/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param amount The amount bid, in ISK
 * @param bidId Unique ID for the bid
 * @param bidderId Character ID of the bidder
 * @param dateBid Datetime when the bid was placed
 */

data class GetCorporationsCorporationIdContractsContractIdBids200Ok (
    /* The amount bid, in ISK */
    @Json(name = "amount")
    var amount: kotlin.Float,
    /* Unique ID for the bid */
    @Json(name = "bid_id")
    var bidId: kotlin.Int,
    /* Character ID of the bidder */
    @Json(name = "bidder_id")
    var bidderId: kotlin.Int,
    /* Datetime when the bid was placed */
    @Json(name = "date_bid")
    var dateBid: java.time.OffsetDateTime
)

