/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param facilityId facility_id integer
 * @param systemId system_id integer
 * @param typeId type_id integer
 */

data class GetCorporationsCorporationIdFacilities200Ok (
    /* facility_id integer */
    @Json(name = "facility_id")
    var facilityId: kotlin.Long,
    /* system_id integer */
    @Json(name = "system_id")
    var systemId: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

