/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdLink
import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdPin
import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdRoute

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param links links array
 * @param pins pins array
 * @param routes routes array
 */

data class GetCharactersCharacterIdPlanetsPlanetIdOk (
    /* links array */
    @Json(name = "links")
    var links: kotlin.Array<GetCharactersCharacterIdPlanetsPlanetIdLink>,
    /* pins array */
    @Json(name = "pins")
    var pins: kotlin.Array<GetCharactersCharacterIdPlanetsPlanetIdPin>,
    /* routes array */
    @Json(name = "routes")
    var routes: kotlin.Array<GetCharactersCharacterIdPlanetsPlanetIdRoute>
)

