/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param accruedRemapCooldownDate Neural remapping cooldown after a character uses remap accrued over time
 * @param bonusRemaps Number of available bonus character neural remaps
 * @param charisma charisma integer
 * @param intelligence intelligence integer
 * @param lastRemapDate Datetime of last neural remap, including usage of bonus remaps
 * @param memory memory integer
 * @param perception perception integer
 * @param willpower willpower integer
 */

data class GetCharactersCharacterIdAttributesOk (
    /* Neural remapping cooldown after a character uses remap accrued over time */
    @Json(name = "accrued_remap_cooldown_date")
    var accruedRemapCooldownDate: java.time.OffsetDateTime? = null,
    /* Number of available bonus character neural remaps */
    @Json(name = "bonus_remaps")
    var bonusRemaps: kotlin.Int? = null,
    /* charisma integer */
    @Json(name = "charisma")
    var charisma: kotlin.Int,
    /* intelligence integer */
    @Json(name = "intelligence")
    var intelligence: kotlin.Int,
    /* Datetime of last neural remap, including usage of bonus remaps */
    @Json(name = "last_remap_date")
    var lastRemapDate: java.time.OffsetDateTime? = null,
    /* memory integer */
    @Json(name = "memory")
    var memory: kotlin.Int,
    /* perception integer */
    @Json(name = "perception")
    var perception: kotlin.Int,
    /* willpower integer */
    @Json(name = "willpower")
    var willpower: kotlin.Int
)

