/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdFittingsItem

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param description description string
 * @param fittingId fitting_id integer
 * @param items items array
 * @param name name string
 * @param shipTypeId ship_type_id integer
 */

data class GetCharactersCharacterIdFittings200Ok (
    /* description string */
    @Json(name = "description")
    var description: kotlin.String,
    /* fitting_id integer */
    @Json(name = "fitting_id")
    var fittingId: kotlin.Int,
    /* items array */
    @Json(name = "items")
    var items: kotlin.Array<GetCharactersCharacterIdFittingsItem>,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    /* ship_type_id integer */
    @Json(name = "ship_type_id")
    var shipTypeId: kotlin.Int
)

