/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param isBlueprintCopy is_blueprint_copy boolean
 * @param isSingleton is_singleton boolean
 * @param itemId item_id integer
 * @param locationFlag location_flag string
 * @param locationId location_id integer
 * @param locationType location_type string
 * @param quantity quantity integer
 * @param typeId type_id integer
 */

data class GetCharactersCharacterIdAssets200Ok (
    /* is_blueprint_copy boolean */
    @Json(name = "is_blueprint_copy")
    var isBlueprintCopy: kotlin.Boolean? = null,
    /* is_singleton boolean */
    @Json(name = "is_singleton")
    var isSingleton: kotlin.Boolean,
    /* item_id integer */
    @Json(name = "item_id")
    var itemId: kotlin.Long,
    /* location_flag string */
    @Json(name = "location_flag")
    var locationFlag: GetCharactersCharacterIdAssets200Ok.LocationFlag,
    /* location_id integer */
    @Json(name = "location_id")
    var locationId: kotlin.Long,
    /* location_type string */
    @Json(name = "location_type")
    var locationType: GetCharactersCharacterIdAssets200Ok.LocationType,
    /* quantity integer */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
) {

    /**
    * location_flag string
    * Values: assetSafety,autoFit,boosterBay,cargo,corpseBay,deliveries,droneBay,fighterBay,fighterTube0,fighterTube1,fighterTube2,fighterTube3,fighterTube4,fleetHangar,frigateEscapeBay,hangar,hangarAll,hiSlot0,hiSlot1,hiSlot2,hiSlot3,hiSlot4,hiSlot5,hiSlot6,hiSlot7,hiddenModifiers,implant,loSlot0,loSlot1,loSlot2,loSlot3,loSlot4,loSlot5,loSlot6,loSlot7,locked,medSlot0,medSlot1,medSlot2,medSlot3,medSlot4,medSlot5,medSlot6,medSlot7,quafeBay,rigSlot0,rigSlot1,rigSlot2,rigSlot3,rigSlot4,rigSlot5,rigSlot6,rigSlot7,shipHangar,skill,specializedAmmoHold,specializedCommandCenterHold,specializedFuelBay,specializedGasHold,specializedIndustrialShipHold,specializedLargeShipHold,specializedMaterialBay,specializedMediumShipHold,specializedMineralHold,specializedOreHold,specializedPlanetaryCommoditiesHold,specializedSalvageHold,specializedShipHold,specializedSmallShipHold,subSystemBay,subSystemSlot0,subSystemSlot1,subSystemSlot2,subSystemSlot3,subSystemSlot4,subSystemSlot5,subSystemSlot6,subSystemSlot7,unlocked,wardrobe
    */
    
    enum class LocationFlag(val value: kotlin.String){
        @Json(name = "AssetSafety") assetSafety("AssetSafety"),
        @Json(name = "AutoFit") autoFit("AutoFit"),
        @Json(name = "BoosterBay") boosterBay("BoosterBay"),
        @Json(name = "Cargo") cargo("Cargo"),
        @Json(name = "CorpseBay") corpseBay("CorpseBay"),
        @Json(name = "Deliveries") deliveries("Deliveries"),
        @Json(name = "DroneBay") droneBay("DroneBay"),
        @Json(name = "FighterBay") fighterBay("FighterBay"),
        @Json(name = "FighterTube0") fighterTube0("FighterTube0"),
        @Json(name = "FighterTube1") fighterTube1("FighterTube1"),
        @Json(name = "FighterTube2") fighterTube2("FighterTube2"),
        @Json(name = "FighterTube3") fighterTube3("FighterTube3"),
        @Json(name = "FighterTube4") fighterTube4("FighterTube4"),
        @Json(name = "FleetHangar") fleetHangar("FleetHangar"),
        @Json(name = "FrigateEscapeBay") frigateEscapeBay("FrigateEscapeBay"),
        @Json(name = "Hangar") hangar("Hangar"),
        @Json(name = "HangarAll") hangarAll("HangarAll"),
        @Json(name = "HiSlot0") hiSlot0("HiSlot0"),
        @Json(name = "HiSlot1") hiSlot1("HiSlot1"),
        @Json(name = "HiSlot2") hiSlot2("HiSlot2"),
        @Json(name = "HiSlot3") hiSlot3("HiSlot3"),
        @Json(name = "HiSlot4") hiSlot4("HiSlot4"),
        @Json(name = "HiSlot5") hiSlot5("HiSlot5"),
        @Json(name = "HiSlot6") hiSlot6("HiSlot6"),
        @Json(name = "HiSlot7") hiSlot7("HiSlot7"),
        @Json(name = "HiddenModifiers") hiddenModifiers("HiddenModifiers"),
        @Json(name = "Implant") implant("Implant"),
        @Json(name = "LoSlot0") loSlot0("LoSlot0"),
        @Json(name = "LoSlot1") loSlot1("LoSlot1"),
        @Json(name = "LoSlot2") loSlot2("LoSlot2"),
        @Json(name = "LoSlot3") loSlot3("LoSlot3"),
        @Json(name = "LoSlot4") loSlot4("LoSlot4"),
        @Json(name = "LoSlot5") loSlot5("LoSlot5"),
        @Json(name = "LoSlot6") loSlot6("LoSlot6"),
        @Json(name = "LoSlot7") loSlot7("LoSlot7"),
        @Json(name = "Locked") locked("Locked"),
        @Json(name = "MedSlot0") medSlot0("MedSlot0"),
        @Json(name = "MedSlot1") medSlot1("MedSlot1"),
        @Json(name = "MedSlot2") medSlot2("MedSlot2"),
        @Json(name = "MedSlot3") medSlot3("MedSlot3"),
        @Json(name = "MedSlot4") medSlot4("MedSlot4"),
        @Json(name = "MedSlot5") medSlot5("MedSlot5"),
        @Json(name = "MedSlot6") medSlot6("MedSlot6"),
        @Json(name = "MedSlot7") medSlot7("MedSlot7"),
        @Json(name = "QuafeBay") quafeBay("QuafeBay"),
        @Json(name = "RigSlot0") rigSlot0("RigSlot0"),
        @Json(name = "RigSlot1") rigSlot1("RigSlot1"),
        @Json(name = "RigSlot2") rigSlot2("RigSlot2"),
        @Json(name = "RigSlot3") rigSlot3("RigSlot3"),
        @Json(name = "RigSlot4") rigSlot4("RigSlot4"),
        @Json(name = "RigSlot5") rigSlot5("RigSlot5"),
        @Json(name = "RigSlot6") rigSlot6("RigSlot6"),
        @Json(name = "RigSlot7") rigSlot7("RigSlot7"),
        @Json(name = "ShipHangar") shipHangar("ShipHangar"),
        @Json(name = "Skill") skill("Skill"),
        @Json(name = "SpecializedAmmoHold") specializedAmmoHold("SpecializedAmmoHold"),
        @Json(name = "SpecializedCommandCenterHold") specializedCommandCenterHold("SpecializedCommandCenterHold"),
        @Json(name = "SpecializedFuelBay") specializedFuelBay("SpecializedFuelBay"),
        @Json(name = "SpecializedGasHold") specializedGasHold("SpecializedGasHold"),
        @Json(name = "SpecializedIndustrialShipHold") specializedIndustrialShipHold("SpecializedIndustrialShipHold"),
        @Json(name = "SpecializedLargeShipHold") specializedLargeShipHold("SpecializedLargeShipHold"),
        @Json(name = "SpecializedMaterialBay") specializedMaterialBay("SpecializedMaterialBay"),
        @Json(name = "SpecializedMediumShipHold") specializedMediumShipHold("SpecializedMediumShipHold"),
        @Json(name = "SpecializedMineralHold") specializedMineralHold("SpecializedMineralHold"),
        @Json(name = "SpecializedOreHold") specializedOreHold("SpecializedOreHold"),
        @Json(name = "SpecializedPlanetaryCommoditiesHold") specializedPlanetaryCommoditiesHold("SpecializedPlanetaryCommoditiesHold"),
        @Json(name = "SpecializedSalvageHold") specializedSalvageHold("SpecializedSalvageHold"),
        @Json(name = "SpecializedShipHold") specializedShipHold("SpecializedShipHold"),
        @Json(name = "SpecializedSmallShipHold") specializedSmallShipHold("SpecializedSmallShipHold"),
        @Json(name = "SubSystemBay") subSystemBay("SubSystemBay"),
        @Json(name = "SubSystemSlot0") subSystemSlot0("SubSystemSlot0"),
        @Json(name = "SubSystemSlot1") subSystemSlot1("SubSystemSlot1"),
        @Json(name = "SubSystemSlot2") subSystemSlot2("SubSystemSlot2"),
        @Json(name = "SubSystemSlot3") subSystemSlot3("SubSystemSlot3"),
        @Json(name = "SubSystemSlot4") subSystemSlot4("SubSystemSlot4"),
        @Json(name = "SubSystemSlot5") subSystemSlot5("SubSystemSlot5"),
        @Json(name = "SubSystemSlot6") subSystemSlot6("SubSystemSlot6"),
        @Json(name = "SubSystemSlot7") subSystemSlot7("SubSystemSlot7"),
        @Json(name = "Unlocked") unlocked("Unlocked"),
        @Json(name = "Wardrobe") wardrobe("Wardrobe");
    }
    /**
    * location_type string
    * Values: station,solarSystem,item,other
    */
    
    enum class LocationType(val value: kotlin.String){
        @Json(name = "station") station("station"),
        @Json(name = "solar_system") solarSystem("solar_system"),
        @Json(name = "item") item("item"),
        @Json(name = "other") other("other");
    }
}

