/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * character_id and response of an attendee
 * @param characterId character_id integer
 * @param eventResponse event_response string
 */

data class GetCharactersCharacterIdCalendarEventIdAttendees200Ok (
    /* character_id integer */
    @Json(name = "character_id")
    var characterId: kotlin.Int? = null,
    /* event_response string */
    @Json(name = "event_response")
    var eventResponse: GetCharactersCharacterIdCalendarEventIdAttendees200Ok.EventResponse? = null
) {

    /**
    * event_response string
    * Values: declined,notResponded,accepted,tentative
    */
    
    enum class EventResponse(val value: kotlin.String){
        @Json(name = "declined") declined("declined"),
        @Json(name = "not_responded") notResponded("not_responded"),
        @Json(name = "accepted") accepted("accepted"),
        @Json(name = "tentative") tentative("tentative");
    }
}

