/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdHead

import com.squareup.moshi.Json
/**
 * extractor_details object
 * @param cycleTime in seconds
 * @param headRadius head_radius number
 * @param heads heads array
 * @param productTypeId product_type_id integer
 * @param qtyPerCycle qty_per_cycle integer
 */

data class GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails (
    /* in seconds */
    @Json(name = "cycle_time")
    var cycleTime: kotlin.Int? = null,
    /* head_radius number */
    @Json(name = "head_radius")
    var headRadius: kotlin.Float? = null,
    /* heads array */
    @Json(name = "heads")
    var heads: kotlin.Array<GetCharactersCharacterIdPlanetsPlanetIdHead>,
    /* product_type_id integer */
    @Json(name = "product_type_id")
    var productTypeId: kotlin.Int? = null,
    /* qty_per_cycle integer */
    @Json(name = "qty_per_cycle")
    var qtyPerCycle: kotlin.Int? = null
)

