/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * Summary of victory points gained by the given corporation for the enlisted faction
 * @param lastWeek Last week's victory points gained by members of the given corporation
 * @param total Total victory points gained since the given corporation enlisted
 * @param yesterday Yesterday's victory points gained by members of the given corporation
 */

data class GetCorporationsCorporationIdFwStatsVictoryPoints (
    /* Last week's victory points gained by members of the given corporation */
    @Json(name = "last_week")
    var lastWeek: kotlin.Int,
    /* Total victory points gained since the given corporation enlisted */
    @Json(name = "total")
    var total: kotlin.Int,
    /* Yesterday's victory points gained by members of the given corporation */
    @Json(name = "yesterday")
    var yesterday: kotlin.Int
)

