/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param buyout Buyout price (for Auctions only)
 * @param collateral Collateral price (for Couriers only)
 * @param contractId contract_id integer
 * @param dateExpired Expiration date of the contract
 * @param dateIssued Сreation date of the contract
 * @param daysToComplete Number of days to perform the contract
 * @param endLocationId End location ID (for Couriers contract)
 * @param forCorporation true if the contract was issued on behalf of the issuer's corporation
 * @param issuerCorporationId Character's corporation ID for the issuer
 * @param issuerId Character ID for the issuer
 * @param price Price of contract (for ItemsExchange and Auctions)
 * @param reward Remuneration for contract (for Couriers only)
 * @param startLocationId Start location ID (for Couriers contract)
 * @param title Title of the contract
 * @param type Type of the contract
 * @param volume Volume of items in the contract
 */

data class GetContractsPublicRegionId200Ok (
    /* Buyout price (for Auctions only) */
    @Json(name = "buyout")
    var buyout: kotlin.Double? = null,
    /* Collateral price (for Couriers only) */
    @Json(name = "collateral")
    var collateral: kotlin.Double? = null,
    /* contract_id integer */
    @Json(name = "contract_id")
    var contractId: kotlin.Int,
    /* Expiration date of the contract */
    @Json(name = "date_expired")
    var dateExpired: java.time.OffsetDateTime,
    /* Сreation date of the contract */
    @Json(name = "date_issued")
    var dateIssued: java.time.OffsetDateTime,
    /* Number of days to perform the contract */
    @Json(name = "days_to_complete")
    var daysToComplete: kotlin.Int? = null,
    /* End location ID (for Couriers contract) */
    @Json(name = "end_location_id")
    var endLocationId: kotlin.Long? = null,
    /* true if the contract was issued on behalf of the issuer's corporation */
    @Json(name = "for_corporation")
    var forCorporation: kotlin.Boolean? = null,
    /* Character's corporation ID for the issuer */
    @Json(name = "issuer_corporation_id")
    var issuerCorporationId: kotlin.Int,
    /* Character ID for the issuer */
    @Json(name = "issuer_id")
    var issuerId: kotlin.Int,
    /* Price of contract (for ItemsExchange and Auctions) */
    @Json(name = "price")
    var price: kotlin.Double? = null,
    /* Remuneration for contract (for Couriers only) */
    @Json(name = "reward")
    var reward: kotlin.Double? = null,
    /* Start location ID (for Couriers contract) */
    @Json(name = "start_location_id")
    var startLocationId: kotlin.Long? = null,
    /* Title of the contract */
    @Json(name = "title")
    var title: kotlin.String? = null,
    /* Type of the contract */
    @Json(name = "type")
    var type: GetContractsPublicRegionId200Ok.Type,
    /* Volume of items in the contract */
    @Json(name = "volume")
    var volume: kotlin.Double? = null
) {

    /**
    * Type of the contract
    * Values: unknown,itemExchange,auction,courier,loan
    */
    
    enum class Type(val value: kotlin.String){
        @Json(name = "unknown") unknown("unknown"),
        @Json(name = "item_exchange") itemExchange("item_exchange"),
        @Json(name = "auction") auction("auction"),
        @Json(name = "courier") courier("courier"),
        @Json(name = "loan") loan("loan");
    }
}

