/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param corporationId corporation_id integer
 * @param loyaltyPoints loyalty_points integer
 */

data class GetCharactersCharacterIdLoyaltyPoints200Ok (
    /* corporation_id integer */
    @Json(name = "corporation_id")
    var corporationId: kotlin.Int,
    /* loyalty_points integer */
    @Json(name = "loyalty_points")
    var loyaltyPoints: kotlin.Int
)

