/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param itemId Unique ID for this item.
 * @param locationFlag Type of the location_id
 * @param locationId References a station, a ship or an item_id if this blueprint is located within a container. If the return value is an item_id, then the Character AssetList API must be queried to find the container using the given item_id to determine the correct location of the Blueprint.
 * @param materialEfficiency Material Efficiency Level of the blueprint.
 * @param quantity A range of numbers with a minimum of -2 and no maximum value where -1 is an original and -2 is a copy. It can be a positive integer if it is a stack of blueprint originals fresh from the market (e.g. no activities performed on them yet).
 * @param runs Number of runs remaining if the blueprint is a copy, -1 if it is an original.
 * @param timeEfficiency Time Efficiency Level of the blueprint.
 * @param typeId type_id integer
 */

data class GetCharactersCharacterIdBlueprints200Ok (
    /* Unique ID for this item. */
    @Json(name = "item_id")
    var itemId: kotlin.Long,
    /* Type of the location_id */
    @Json(name = "location_flag")
    var locationFlag: GetCharactersCharacterIdBlueprints200Ok.LocationFlag,
    /* References a station, a ship or an item_id if this blueprint is located within a container. If the return value is an item_id, then the Character AssetList API must be queried to find the container using the given item_id to determine the correct location of the Blueprint. */
    @Json(name = "location_id")
    var locationId: kotlin.Long,
    /* Material Efficiency Level of the blueprint. */
    @Json(name = "material_efficiency")
    var materialEfficiency: kotlin.Int,
    /* A range of numbers with a minimum of -2 and no maximum value where -1 is an original and -2 is a copy. It can be a positive integer if it is a stack of blueprint originals fresh from the market (e.g. no activities performed on them yet). */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* Number of runs remaining if the blueprint is a copy, -1 if it is an original. */
    @Json(name = "runs")
    var runs: kotlin.Int,
    /* Time Efficiency Level of the blueprint. */
    @Json(name = "time_efficiency")
    var timeEfficiency: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
) {

    /**
    * Type of the location_id
    * Values: autoFit,cargo,corpseBay,droneBay,fleetHangar,deliveries,hiddenModifiers,hangar,hangarAll,loSlot0,loSlot1,loSlot2,loSlot3,loSlot4,loSlot5,loSlot6,loSlot7,medSlot0,medSlot1,medSlot2,medSlot3,medSlot4,medSlot5,medSlot6,medSlot7,hiSlot0,hiSlot1,hiSlot2,hiSlot3,hiSlot4,hiSlot5,hiSlot6,hiSlot7,assetSafety,locked,unlocked,implant,quafeBay,rigSlot0,rigSlot1,rigSlot2,rigSlot3,rigSlot4,rigSlot5,rigSlot6,rigSlot7,shipHangar,specializedFuelBay,specializedOreHold,specializedGasHold,specializedMineralHold,specializedSalvageHold,specializedShipHold,specializedSmallShipHold,specializedMediumShipHold,specializedLargeShipHold,specializedIndustrialShipHold,specializedAmmoHold,specializedCommandCenterHold,specializedPlanetaryCommoditiesHold,specializedMaterialBay,subSystemSlot0,subSystemSlot1,subSystemSlot2,subSystemSlot3,subSystemSlot4,subSystemSlot5,subSystemSlot6,subSystemSlot7,fighterBay,fighterTube0,fighterTube1,fighterTube2,fighterTube3,fighterTube4,module
    */
    
    enum class LocationFlag(val value: kotlin.String){
        @Json(name = "AutoFit") autoFit("AutoFit"),
        @Json(name = "Cargo") cargo("Cargo"),
        @Json(name = "CorpseBay") corpseBay("CorpseBay"),
        @Json(name = "DroneBay") droneBay("DroneBay"),
        @Json(name = "FleetHangar") fleetHangar("FleetHangar"),
        @Json(name = "Deliveries") deliveries("Deliveries"),
        @Json(name = "HiddenModifiers") hiddenModifiers("HiddenModifiers"),
        @Json(name = "Hangar") hangar("Hangar"),
        @Json(name = "HangarAll") hangarAll("HangarAll"),
        @Json(name = "LoSlot0") loSlot0("LoSlot0"),
        @Json(name = "LoSlot1") loSlot1("LoSlot1"),
        @Json(name = "LoSlot2") loSlot2("LoSlot2"),
        @Json(name = "LoSlot3") loSlot3("LoSlot3"),
        @Json(name = "LoSlot4") loSlot4("LoSlot4"),
        @Json(name = "LoSlot5") loSlot5("LoSlot5"),
        @Json(name = "LoSlot6") loSlot6("LoSlot6"),
        @Json(name = "LoSlot7") loSlot7("LoSlot7"),
        @Json(name = "MedSlot0") medSlot0("MedSlot0"),
        @Json(name = "MedSlot1") medSlot1("MedSlot1"),
        @Json(name = "MedSlot2") medSlot2("MedSlot2"),
        @Json(name = "MedSlot3") medSlot3("MedSlot3"),
        @Json(name = "MedSlot4") medSlot4("MedSlot4"),
        @Json(name = "MedSlot5") medSlot5("MedSlot5"),
        @Json(name = "MedSlot6") medSlot6("MedSlot6"),
        @Json(name = "MedSlot7") medSlot7("MedSlot7"),
        @Json(name = "HiSlot0") hiSlot0("HiSlot0"),
        @Json(name = "HiSlot1") hiSlot1("HiSlot1"),
        @Json(name = "HiSlot2") hiSlot2("HiSlot2"),
        @Json(name = "HiSlot3") hiSlot3("HiSlot3"),
        @Json(name = "HiSlot4") hiSlot4("HiSlot4"),
        @Json(name = "HiSlot5") hiSlot5("HiSlot5"),
        @Json(name = "HiSlot6") hiSlot6("HiSlot6"),
        @Json(name = "HiSlot7") hiSlot7("HiSlot7"),
        @Json(name = "AssetSafety") assetSafety("AssetSafety"),
        @Json(name = "Locked") locked("Locked"),
        @Json(name = "Unlocked") unlocked("Unlocked"),
        @Json(name = "Implant") implant("Implant"),
        @Json(name = "QuafeBay") quafeBay("QuafeBay"),
        @Json(name = "RigSlot0") rigSlot0("RigSlot0"),
        @Json(name = "RigSlot1") rigSlot1("RigSlot1"),
        @Json(name = "RigSlot2") rigSlot2("RigSlot2"),
        @Json(name = "RigSlot3") rigSlot3("RigSlot3"),
        @Json(name = "RigSlot4") rigSlot4("RigSlot4"),
        @Json(name = "RigSlot5") rigSlot5("RigSlot5"),
        @Json(name = "RigSlot6") rigSlot6("RigSlot6"),
        @Json(name = "RigSlot7") rigSlot7("RigSlot7"),
        @Json(name = "ShipHangar") shipHangar("ShipHangar"),
        @Json(name = "SpecializedFuelBay") specializedFuelBay("SpecializedFuelBay"),
        @Json(name = "SpecializedOreHold") specializedOreHold("SpecializedOreHold"),
        @Json(name = "SpecializedGasHold") specializedGasHold("SpecializedGasHold"),
        @Json(name = "SpecializedMineralHold") specializedMineralHold("SpecializedMineralHold"),
        @Json(name = "SpecializedSalvageHold") specializedSalvageHold("SpecializedSalvageHold"),
        @Json(name = "SpecializedShipHold") specializedShipHold("SpecializedShipHold"),
        @Json(name = "SpecializedSmallShipHold") specializedSmallShipHold("SpecializedSmallShipHold"),
        @Json(name = "SpecializedMediumShipHold") specializedMediumShipHold("SpecializedMediumShipHold"),
        @Json(name = "SpecializedLargeShipHold") specializedLargeShipHold("SpecializedLargeShipHold"),
        @Json(name = "SpecializedIndustrialShipHold") specializedIndustrialShipHold("SpecializedIndustrialShipHold"),
        @Json(name = "SpecializedAmmoHold") specializedAmmoHold("SpecializedAmmoHold"),
        @Json(name = "SpecializedCommandCenterHold") specializedCommandCenterHold("SpecializedCommandCenterHold"),
        @Json(name = "SpecializedPlanetaryCommoditiesHold") specializedPlanetaryCommoditiesHold("SpecializedPlanetaryCommoditiesHold"),
        @Json(name = "SpecializedMaterialBay") specializedMaterialBay("SpecializedMaterialBay"),
        @Json(name = "SubSystemSlot0") subSystemSlot0("SubSystemSlot0"),
        @Json(name = "SubSystemSlot1") subSystemSlot1("SubSystemSlot1"),
        @Json(name = "SubSystemSlot2") subSystemSlot2("SubSystemSlot2"),
        @Json(name = "SubSystemSlot3") subSystemSlot3("SubSystemSlot3"),
        @Json(name = "SubSystemSlot4") subSystemSlot4("SubSystemSlot4"),
        @Json(name = "SubSystemSlot5") subSystemSlot5("SubSystemSlot5"),
        @Json(name = "SubSystemSlot6") subSystemSlot6("SubSystemSlot6"),
        @Json(name = "SubSystemSlot7") subSystemSlot7("SubSystemSlot7"),
        @Json(name = "FighterBay") fighterBay("FighterBay"),
        @Json(name = "FighterTube0") fighterTube0("FighterTube0"),
        @Json(name = "FighterTube1") fighterTube1("FighterTube1"),
        @Json(name = "FighterTube2") fighterTube2("FighterTube2"),
        @Json(name = "FighterTube3") fighterTube3("FighterTube3"),
        @Json(name = "FighterTube4") fighterTube4("FighterTube4"),
        @Json(name = "Module") module("Module");
    }
}

