/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param lastLogin Timestamp of the last login
 * @param lastLogout Timestamp of the last logout
 * @param logins Total number of times the character has logged in
 * @param online If the character is online
 */

data class GetCharactersCharacterIdOnlineOk (
    /* Timestamp of the last login */
    @Json(name = "last_login")
    var lastLogin: java.time.OffsetDateTime? = null,
    /* Timestamp of the last logout */
    @Json(name = "last_logout")
    var lastLogout: java.time.OffsetDateTime? = null,
    /* Total number of times the character has logged in */
    @Json(name = "logins")
    var logins: kotlin.Int? = null,
    /* If the character is online */
    @Json(name = "online")
    var online: kotlin.Boolean
)

