/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param jumpFatigueExpireDate Character's jump fatigue expiry
 * @param lastJumpDate Character's last jump activation
 * @param lastUpdateDate Character's last jump update
 */

data class GetCharactersCharacterIdFatigueOk (
    /* Character's jump fatigue expiry */
    @Json(name = "jump_fatigue_expire_date")
    var jumpFatigueExpireDate: java.time.OffsetDateTime? = null,
    /* Character's last jump activation */
    @Json(name = "last_jump_date")
    var lastJumpDate: java.time.OffsetDateTime? = null,
    /* Character's last jump update */
    @Json(name = "last_update_date")
    var lastUpdateDate: java.time.OffsetDateTime? = null
)

