/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param characterId character_id integer
 * @param titles A list of title_id
 */

data class GetCorporationsCorporationIdMembersTitles200Ok (
    /* character_id integer */
    @Json(name = "character_id")
    var characterId: kotlin.Int,
    /* A list of title_id */
    @Json(name = "titles")
    var titles: kotlin.Array<kotlin.Int>
)

