/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * wallet transaction
 * @param clientId client_id integer
 * @param date Date and time of transaction
 * @param isBuy is_buy boolean
 * @param journalRefId -1 if there is no corresponding wallet journal entry
 * @param locationId location_id integer
 * @param quantity quantity integer
 * @param transactionId Unique transaction ID
 * @param typeId type_id integer
 * @param unitPrice Amount paid per unit
 */

data class GetCorporationsCorporationIdWalletsDivisionTransactions200Ok (
    /* client_id integer */
    @Json(name = "client_id")
    var clientId: kotlin.Int,
    /* Date and time of transaction */
    @Json(name = "date")
    var date: java.time.OffsetDateTime,
    /* is_buy boolean */
    @Json(name = "is_buy")
    var isBuy: kotlin.Boolean,
    /* -1 if there is no corresponding wallet journal entry */
    @Json(name = "journal_ref_id")
    var journalRefId: kotlin.Long,
    /* location_id integer */
    @Json(name = "location_id")
    var locationId: kotlin.Long,
    /* quantity integer */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* Unique transaction ID */
    @Json(name = "transaction_id")
    var transactionId: kotlin.Long,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int,
    /* Amount paid per unit */
    @Json(name = "unit_price")
    var unitPrice: kotlin.Double
)

