/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param px128x128 px128x128 string
 * @param px256x256 px256x256 string
 * @param px64x64 px64x64 string
 */

data class GetCorporationsCorporationIdIconsOk (
    /* px128x128 string */
    @Json(name = "px128x128")
    var px128x128: kotlin.String? = null,
    /* px256x256 string */
    @Json(name = "px256x256")
    var px256x256: kotlin.String? = null,
    /* px64x64 string */
    @Json(name = "px64x64")
    var px64x64: kotlin.String? = null
)

