/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param folderId folder_id integer
 * @param name name string
 */

data class GetCharactersCharacterIdBookmarksFolders200Ok (
    /* folder_id integer */
    @Json(name = "folder_id")
    var folderId: kotlin.Int,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String
)

