/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * event
 * @param eventDate event_date string
 * @param eventId event_id integer
 * @param eventResponse event_response string
 * @param importance importance integer
 * @param title title string
 */

data class GetCharactersCharacterIdCalendar200Ok (
    /* event_date string */
    @Json(name = "event_date")
    var eventDate: java.time.OffsetDateTime? = null,
    /* event_id integer */
    @Json(name = "event_id")
    var eventId: kotlin.Int? = null,
    /* event_response string */
    @Json(name = "event_response")
    var eventResponse: GetCharactersCharacterIdCalendar200Ok.EventResponse? = null,
    /* importance integer */
    @Json(name = "importance")
    var importance: kotlin.Int? = null,
    /* title string */
    @Json(name = "title")
    var title: kotlin.String? = null
) {

    /**
    * event_response string
    * Values: declined,notResponded,accepted,tentative
    */
    
    enum class EventResponse(val value: kotlin.String){
        @Json(name = "declined") declined("declined"),
        @Json(name = "not_responded") notResponded("not_responded"),
        @Json(name = "accepted") accepted("accepted"),
        @Json(name = "tentative") tentative("tentative");
    }
}

