/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param labelId label_id integer
 * @param labelName label_name string
 */

data class GetCharactersCharacterIdContactsLabels200Ok (
    /* label_id integer */
    @Json(name = "label_id")
    var labelId: kotlin.Long,
    /* label_name string */
    @Json(name = "label_name")
    var labelName: kotlin.String
)

