/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdMailMailIdRecipient

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param body Mail's body
 * @param from From whom the mail was sent
 * @param labels Labels attached to the mail
 * @param read Whether the mail is flagged as read
 * @param recipients Recipients of the mail
 * @param subject Mail subject
 * @param timestamp When the mail was sent
 */

data class GetCharactersCharacterIdMailMailIdOk (
    /* Mail's body */
    @Json(name = "body")
    var body: kotlin.String? = null,
    /* From whom the mail was sent */
    @Json(name = "from")
    var from: kotlin.Int? = null,
    /* Labels attached to the mail */
    @Json(name = "labels")
    var labels: kotlin.Array<kotlin.Int>? = null,
    /* Whether the mail is flagged as read */
    @Json(name = "read")
    var read: kotlin.Boolean? = null,
    /* Recipients of the mail */
    @Json(name = "recipients")
    var recipients: kotlin.collections.Set<GetCharactersCharacterIdMailMailIdRecipient>? = null,
    /* Mail subject */
    @Json(name = "subject")
    var subject: kotlin.String? = null,
    /* When the mail was sent */
    @Json(name = "timestamp")
    var timestamp: java.time.OffsetDateTime? = null
)

