/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdContent
import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails
import tv.z85.esi.models.GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails

import com.squareup.moshi.Json
/**
 * pin object
 * @param contents contents array
 * @param expiryTime expiry_time string
 * @param extractorDetails 
 * @param factoryDetails 
 * @param installTime install_time string
 * @param lastCycleStart last_cycle_start string
 * @param latitude latitude number
 * @param longitude longitude number
 * @param pinId pin_id integer
 * @param schematicId schematic_id integer
 * @param typeId type_id integer
 */

data class GetCharactersCharacterIdPlanetsPlanetIdPin (
    /* contents array */
    @Json(name = "contents")
    var contents: kotlin.Array<GetCharactersCharacterIdPlanetsPlanetIdContent>? = null,
    /* expiry_time string */
    @Json(name = "expiry_time")
    var expiryTime: java.time.OffsetDateTime? = null,
    @Json(name = "extractor_details")
    var extractorDetails: GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails? = null,
    @Json(name = "factory_details")
    var factoryDetails: GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails? = null,
    /* install_time string */
    @Json(name = "install_time")
    var installTime: java.time.OffsetDateTime? = null,
    /* last_cycle_start string */
    @Json(name = "last_cycle_start")
    var lastCycleStart: java.time.OffsetDateTime? = null,
    /* latitude number */
    @Json(name = "latitude")
    var latitude: kotlin.Float,
    /* longitude number */
    @Json(name = "longitude")
    var longitude: kotlin.Float,
    /* pin_id integer */
    @Json(name = "pin_id")
    var pinId: kotlin.Long,
    /* schematic_id integer */
    @Json(name = "schematic_id")
    var schematicId: kotlin.Int? = null,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

