/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * dogma_attribute object
 * @param attributeId attribute_id integer
 * @param value value number
 */

data class GetDogmaDynamicItemsTypeIdItemIdDogmaAttribute (
    /* attribute_id integer */
    @Json(name = "attribute_id")
    var attributeId: kotlin.Int,
    /* value number */
    @Json(name = "value")
    var value: kotlin.Float
)

