/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param isFreeMove Is free-move enabled
 * @param isRegistered Does the fleet have an active fleet advertisement
 * @param isVoiceEnabled Is EVE Voice enabled
 * @param motd Fleet MOTD in CCP flavoured HTML
 */

data class GetFleetsFleetIdOk (
    /* Is free-move enabled */
    @Json(name = "is_free_move")
    var isFreeMove: kotlin.Boolean,
    /* Does the fleet have an active fleet advertisement */
    @Json(name = "is_registered")
    var isRegistered: kotlin.Boolean,
    /* Is EVE Voice enabled */
    @Json(name = "is_voice_enabled")
    var isVoiceEnabled: kotlin.Boolean,
    /* Fleet MOTD in CCP flavoured HTML */
    @Json(name = "motd")
    var motd: kotlin.String
)

