/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * yesterday object
 * @param amount Amount of victory points
 * @param corporationId corporation_id integer
 */

data class GetFwLeaderboardsCorporationsYesterdayYesterday1 (
    /* Amount of victory points */
    @Json(name = "amount")
    var amount: kotlin.Int? = null,
    /* corporation_id integer */
    @Json(name = "corporation_id")
    var corporationId: kotlin.Int? = null
)

