/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetFwLeaderboardsActiveTotalActiveTotal1
import tv.z85.esi.models.GetFwLeaderboardsLastWeekLastWeek1
import tv.z85.esi.models.GetFwLeaderboardsYesterdayYesterday1

import com.squareup.moshi.Json
/**
 * Top 4 rankings of factions by victory points from yesterday, last week and in total
 * @param activeTotal Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days
 * @param lastWeek Top 4 ranking of factions by victory points in the past week
 * @param yesterday Top 4 ranking of factions by victory points in the past day
 */

data class GetFwLeaderboardsVictoryPoints (
    /* Top 4 ranking of factions active in faction warfare by total victory points. A faction is considered \"active\" if they have participated in faction warfare in the past 14 days */
    @Json(name = "active_total")
    var activeTotal: kotlin.Array<GetFwLeaderboardsActiveTotalActiveTotal1>,
    /* Top 4 ranking of factions by victory points in the past week */
    @Json(name = "last_week")
    var lastWeek: kotlin.Array<GetFwLeaderboardsLastWeekLastWeek1>,
    /* Top 4 ranking of factions by victory points in the past day */
    @Json(name = "yesterday")
    var yesterday: kotlin.Array<GetFwLeaderboardsYesterdayYesterday1>
)

