/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param facilityId ID of the facility
 * @param ownerId Owner of the facility
 * @param regionId Region ID where the facility is
 * @param solarSystemId Solar system ID where the facility is
 * @param tax Tax imposed by the facility
 * @param typeId Type ID of the facility
 */

data class GetIndustryFacilities200Ok (
    /* ID of the facility */
    @Json(name = "facility_id")
    var facilityId: kotlin.Long,
    /* Owner of the facility */
    @Json(name = "owner_id")
    var ownerId: kotlin.Int,
    /* Region ID where the facility is */
    @Json(name = "region_id")
    var regionId: kotlin.Int,
    /* Solar system ID where the facility is */
    @Json(name = "solar_system_id")
    var solarSystemId: kotlin.Int,
    /* Tax imposed by the facility */
    @Json(name = "tax")
    var tax: kotlin.Float? = null,
    /* Type ID of the facility */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

