/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param constellationId The constellation id in which this incursion takes place
 * @param factionId The attacking faction's id
 * @param hasBoss Whether the final encounter has boss or not
 * @param infestedSolarSystems A list of infested solar system ids that are a part of this incursion
 * @param influence Influence of this incursion as a float from 0 to 1
 * @param stagingSolarSystemId Staging solar system for this incursion
 * @param state The state of this incursion
 * @param type The type of this incursion
 */

data class GetIncursions200Ok (
    /* The constellation id in which this incursion takes place */
    @Json(name = "constellation_id")
    var constellationId: kotlin.Int,
    /* The attacking faction's id */
    @Json(name = "faction_id")
    var factionId: kotlin.Int,
    /* Whether the final encounter has boss or not */
    @Json(name = "has_boss")
    var hasBoss: kotlin.Boolean,
    /* A list of infested solar system ids that are a part of this incursion */
    @Json(name = "infested_solar_systems")
    var infestedSolarSystems: kotlin.Array<kotlin.Int>,
    /* Influence of this incursion as a float from 0 to 1 */
    @Json(name = "influence")
    var influence: kotlin.Float,
    /* Staging solar system for this incursion */
    @Json(name = "staging_solar_system_id")
    var stagingSolarSystemId: kotlin.Int,
    /* The state of this incursion */
    @Json(name = "state")
    var state: GetIncursions200Ok.State,
    /* The type of this incursion */
    @Json(name = "type")
    var type: kotlin.String
) {

    /**
    * The state of this incursion
    * Values: withdrawing,mobilizing,established
    */
    
    enum class State(val value: kotlin.String){
        @Json(name = "withdrawing") withdrawing("withdrawing"),
        @Json(name = "mobilizing") mobilizing("mobilizing"),
        @Json(name = "established") established("established");
    }
}

