/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetKillmailsKillmailIdKillmailHashItemsItem

import com.squareup.moshi.Json
/**
 * item object
 * @param flag Flag for the location of the item 
 * @param itemTypeId item_type_id integer
 * @param items items array
 * @param quantityDestroyed How many of the item were destroyed if any 
 * @param quantityDropped How many of the item were dropped if any 
 * @param singleton singleton integer
 */

data class GetKillmailsKillmailIdKillmailHashItem (
    /* Flag for the location of the item  */
    @Json(name = "flag")
    var flag: kotlin.Int,
    /* item_type_id integer */
    @Json(name = "item_type_id")
    var itemTypeId: kotlin.Int,
    /* items array */
    @Json(name = "items")
    var items: kotlin.Array<GetKillmailsKillmailIdKillmailHashItemsItem>? = null,
    /* How many of the item were destroyed if any  */
    @Json(name = "quantity_destroyed")
    var quantityDestroyed: kotlin.Long? = null,
    /* How many of the item were dropped if any  */
    @Json(name = "quantity_dropped")
    var quantityDropped: kotlin.Long? = null,
    /* singleton integer */
    @Json(name = "singleton")
    var singleton: kotlin.Int
)

