/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetKillmailsKillmailIdKillmailHashAttacker
import tv.z85.esi.models.GetKillmailsKillmailIdKillmailHashVictim

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param attackers attackers array
 * @param killmailId ID of the killmail
 * @param killmailTime Time that the victim was killed and the killmail generated 
 * @param moonId Moon if the kill took place at one
 * @param solarSystemId Solar system that the kill took place in 
 * @param victim 
 * @param warId War if the killmail is generated in relation to an official war 
 */

data class GetKillmailsKillmailIdKillmailHashOk (
    /* attackers array */
    @Json(name = "attackers")
    var attackers: kotlin.Array<GetKillmailsKillmailIdKillmailHashAttacker>,
    /* ID of the killmail */
    @Json(name = "killmail_id")
    var killmailId: kotlin.Int,
    /* Time that the victim was killed and the killmail generated  */
    @Json(name = "killmail_time")
    var killmailTime: java.time.OffsetDateTime,
    /* Moon if the kill took place at one */
    @Json(name = "moon_id")
    var moonId: kotlin.Int? = null,
    /* Solar system that the kill took place in  */
    @Json(name = "solar_system_id")
    var solarSystemId: kotlin.Int,
    @Json(name = "victim")
    var victim: GetKillmailsKillmailIdKillmailHashVictim,
    /* War if the killmail is generated in relation to an official war  */
    @Json(name = "war_id")
    var warId: kotlin.Int? = null
)

