/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * required_item object
 * @param quantity quantity integer
 * @param typeId type_id integer
 */

data class GetLoyaltyStoresCorporationIdOffersRequiredItem (
    /* quantity integer */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

