/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetLoyaltyStoresCorporationIdOffersRequiredItem

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param akCost Analysis kredit cost
 * @param iskCost isk_cost integer
 * @param lpCost lp_cost integer
 * @param offerId offer_id integer
 * @param quantity quantity integer
 * @param requiredItems required_items array
 * @param typeId type_id integer
 */

data class GetLoyaltyStoresCorporationIdOffers200Ok (
    /* Analysis kredit cost */
    @Json(name = "ak_cost")
    var akCost: kotlin.Int? = null,
    /* isk_cost integer */
    @Json(name = "isk_cost")
    var iskCost: kotlin.Long,
    /* lp_cost integer */
    @Json(name = "lp_cost")
    var lpCost: kotlin.Int,
    /* offer_id integer */
    @Json(name = "offer_id")
    var offerId: kotlin.Int,
    /* quantity integer */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* required_items array */
    @Json(name = "required_items")
    var requiredItems: kotlin.Array<GetLoyaltyStoresCorporationIdOffersRequiredItem>,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

