/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param adjustedPrice adjusted_price number
 * @param averagePrice average_price number
 * @param typeId type_id integer
 */

data class GetMarketsPrices200Ok (
    /* adjusted_price number */
    @Json(name = "adjusted_price")
    var adjustedPrice: kotlin.Double? = null,
    /* average_price number */
    @Json(name = "average_price")
    var averagePrice: kotlin.Double? = null,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
)

