/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param average average number
 * @param date The date of this historical statistic entry
 * @param highest highest number
 * @param lowest lowest number
 * @param orderCount Total number of orders happened that day
 * @param volume Total
 */

data class GetMarketsRegionIdHistory200Ok (
    /* average number */
    @Json(name = "average")
    var average: kotlin.Double,
    /* The date of this historical statistic entry */
    @Json(name = "date")
    var date: java.time.LocalDate,
    /* highest number */
    @Json(name = "highest")
    var highest: kotlin.Double,
    /* lowest number */
    @Json(name = "lowest")
    var lowest: kotlin.Double,
    /* Total number of orders happened that day */
    @Json(name = "order_count")
    var orderCount: kotlin.Long,
    /* Total */
    @Json(name = "volume")
    var volume: kotlin.Long
)

