/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param connectedGroups The groups that are connected to this group on the opportunities map
 * @param description description string
 * @param groupId group_id integer
 * @param name name string
 * @param notification notification string
 * @param requiredTasks Tasks need to complete for this group
 */

data class GetOpportunitiesGroupsGroupIdOk (
    /* The groups that are connected to this group on the opportunities map */
    @Json(name = "connected_groups")
    var connectedGroups: kotlin.Array<kotlin.Int>,
    /* description string */
    @Json(name = "description")
    var description: kotlin.String,
    /* group_id integer */
    @Json(name = "group_id")
    var groupId: kotlin.Int,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    /* notification string */
    @Json(name = "notification")
    var notification: kotlin.String,
    /* Tasks need to complete for this group */
    @Json(name = "required_tasks")
    var requiredTasks: kotlin.Array<kotlin.Int>
)

