/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param players Current online player count
 * @param serverVersion Running version as string
 * @param startTime Server start timestamp
 * @param vip If the server is in VIP mode
 */

data class GetStatusOk (
    /* Current online player count */
    @Json(name = "players")
    var players: kotlin.Int,
    /* Running version as string */
    @Json(name = "server_version")
    var serverVersion: kotlin.String,
    /* Server start timestamp */
    @Json(name = "start_time")
    var startTime: java.time.OffsetDateTime,
    /* If the server is in VIP mode */
    @Json(name = "vip")
    var vip: kotlin.Boolean? = null
)

