/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param npcKills Number of NPC ships killed in this system
 * @param podKills Number of pods killed in this system
 * @param shipKills Number of player ships killed in this system
 * @param systemId system_id integer
 */

data class GetUniverseSystemKills200Ok (
    /* Number of NPC ships killed in this system */
    @Json(name = "npc_kills")
    var npcKills: kotlin.Int,
    /* Number of pods killed in this system */
    @Json(name = "pod_kills")
    var podKills: kotlin.Int,
    /* Number of player ships killed in this system */
    @Json(name = "ship_kills")
    var shipKills: kotlin.Int,
    /* system_id integer */
    @Json(name = "system_id")
    var systemId: kotlin.Int
)

