/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param collisionFile collision_file string
 * @param graphicFile graphic_file string
 * @param graphicId graphic_id integer
 * @param iconFolder icon_folder string
 * @param sofDna sof_dna string
 * @param sofFationName sof_fation_name string
 * @param sofHullName sof_hull_name string
 * @param sofRaceName sof_race_name string
 */

data class GetUniverseGraphicsGraphicIdOk (
    /* collision_file string */
    @Json(name = "collision_file")
    var collisionFile: kotlin.String? = null,
    /* graphic_file string */
    @Json(name = "graphic_file")
    var graphicFile: kotlin.String? = null,
    /* graphic_id integer */
    @Json(name = "graphic_id")
    var graphicId: kotlin.Int,
    /* icon_folder string */
    @Json(name = "icon_folder")
    var iconFolder: kotlin.String? = null,
    /* sof_dna string */
    @Json(name = "sof_dna")
    var sofDna: kotlin.String? = null,
    /* sof_fation_name string */
    @Json(name = "sof_fation_name")
    var sofFationName: kotlin.String? = null,
    /* sof_hull_name string */
    @Json(name = "sof_hull_name")
    var sofHullName: kotlin.String? = null,
    /* sof_race_name string */
    @Json(name = "sof_race_name")
    var sofRaceName: kotlin.String? = null
)

