/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param age Age of star in years
 * @param luminosity luminosity number
 * @param name name string
 * @param radius radius integer
 * @param solarSystemId solar_system_id integer
 * @param spectralClass spectral_class string
 * @param temperature temperature integer
 * @param typeId type_id integer
 */

data class GetUniverseStarsStarIdOk (
    /* Age of star in years */
    @Json(name = "age")
    var age: kotlin.Long,
    /* luminosity number */
    @Json(name = "luminosity")
    var luminosity: kotlin.Float,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    /* radius integer */
    @Json(name = "radius")
    var radius: kotlin.Long,
    /* solar_system_id integer */
    @Json(name = "solar_system_id")
    var solarSystemId: kotlin.Int,
    /* spectral_class string */
    @Json(name = "spectral_class")
    var spectralClass: GetUniverseStarsStarIdOk.SpectralClass,
    /* temperature integer */
    @Json(name = "temperature")
    var temperature: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
) {

    /**
    * spectral_class string
    * Values: k2V,k4V,g2V,g8V,m7V,k7V,m2V,k5V,m3V,g0V,g7V,g3V,f9V,g5V,f6V,k8V,k9V,k6V,g9V,g6V,g4VI,g4V,f8V,f2V,f1V,k3V,f0VI,g1VI,g0VI,k1V,m4V,m1V,m6V,m0V,k2IV,g2VI,k0V,k5IV,f5VI,g6VI,f6VI,f2IV,g3VI,m8V,f1VI,k1IV,f7V,g5VI,m5V,g7VI,f5V,f4VI,f8VI,k3IV,f4IV,f0V,g7IV,g8VI,f2VI,f4V,f7VI,f3V,g1V,g9VI,f3IV,f9VI,m9V,k0IV,f1IV,g4IV,f3VI,k4IV,g5IV,g3IV,g1IV,k7IV,g0IV,k6IV,k9IV,g2IV,f9IV,f0IV,k8IV,g8IV,f6IV,f5IV,a0,a0IV,a0IV2
    */
    
    enum class SpectralClass(val value: kotlin.String){
        @Json(name = "K2 V") k2V("K2 V"),
        @Json(name = "K4 V") k4V("K4 V"),
        @Json(name = "G2 V") g2V("G2 V"),
        @Json(name = "G8 V") g8V("G8 V"),
        @Json(name = "M7 V") m7V("M7 V"),
        @Json(name = "K7 V") k7V("K7 V"),
        @Json(name = "M2 V") m2V("M2 V"),
        @Json(name = "K5 V") k5V("K5 V"),
        @Json(name = "M3 V") m3V("M3 V"),
        @Json(name = "G0 V") g0V("G0 V"),
        @Json(name = "G7 V") g7V("G7 V"),
        @Json(name = "G3 V") g3V("G3 V"),
        @Json(name = "F9 V") f9V("F9 V"),
        @Json(name = "G5 V") g5V("G5 V"),
        @Json(name = "F6 V") f6V("F6 V"),
        @Json(name = "K8 V") k8V("K8 V"),
        @Json(name = "K9 V") k9V("K9 V"),
        @Json(name = "K6 V") k6V("K6 V"),
        @Json(name = "G9 V") g9V("G9 V"),
        @Json(name = "G6 V") g6V("G6 V"),
        @Json(name = "G4 VI") g4VI("G4 VI"),
        @Json(name = "G4 V") g4V("G4 V"),
        @Json(name = "F8 V") f8V("F8 V"),
        @Json(name = "F2 V") f2V("F2 V"),
        @Json(name = "F1 V") f1V("F1 V"),
        @Json(name = "K3 V") k3V("K3 V"),
        @Json(name = "F0 VI") f0VI("F0 VI"),
        @Json(name = "G1 VI") g1VI("G1 VI"),
        @Json(name = "G0 VI") g0VI("G0 VI"),
        @Json(name = "K1 V") k1V("K1 V"),
        @Json(name = "M4 V") m4V("M4 V"),
        @Json(name = "M1 V") m1V("M1 V"),
        @Json(name = "M6 V") m6V("M6 V"),
        @Json(name = "M0 V") m0V("M0 V"),
        @Json(name = "K2 IV") k2IV("K2 IV"),
        @Json(name = "G2 VI") g2VI("G2 VI"),
        @Json(name = "K0 V") k0V("K0 V"),
        @Json(name = "K5 IV") k5IV("K5 IV"),
        @Json(name = "F5 VI") f5VI("F5 VI"),
        @Json(name = "G6 VI") g6VI("G6 VI"),
        @Json(name = "F6 VI") f6VI("F6 VI"),
        @Json(name = "F2 IV") f2IV("F2 IV"),
        @Json(name = "G3 VI") g3VI("G3 VI"),
        @Json(name = "M8 V") m8V("M8 V"),
        @Json(name = "F1 VI") f1VI("F1 VI"),
        @Json(name = "K1 IV") k1IV("K1 IV"),
        @Json(name = "F7 V") f7V("F7 V"),
        @Json(name = "G5 VI") g5VI("G5 VI"),
        @Json(name = "M5 V") m5V("M5 V"),
        @Json(name = "G7 VI") g7VI("G7 VI"),
        @Json(name = "F5 V") f5V("F5 V"),
        @Json(name = "F4 VI") f4VI("F4 VI"),
        @Json(name = "F8 VI") f8VI("F8 VI"),
        @Json(name = "K3 IV") k3IV("K3 IV"),
        @Json(name = "F4 IV") f4IV("F4 IV"),
        @Json(name = "F0 V") f0V("F0 V"),
        @Json(name = "G7 IV") g7IV("G7 IV"),
        @Json(name = "G8 VI") g8VI("G8 VI"),
        @Json(name = "F2 VI") f2VI("F2 VI"),
        @Json(name = "F4 V") f4V("F4 V"),
        @Json(name = "F7 VI") f7VI("F7 VI"),
        @Json(name = "F3 V") f3V("F3 V"),
        @Json(name = "G1 V") g1V("G1 V"),
        @Json(name = "G9 VI") g9VI("G9 VI"),
        @Json(name = "F3 IV") f3IV("F3 IV"),
        @Json(name = "F9 VI") f9VI("F9 VI"),
        @Json(name = "M9 V") m9V("M9 V"),
        @Json(name = "K0 IV") k0IV("K0 IV"),
        @Json(name = "F1 IV") f1IV("F1 IV"),
        @Json(name = "G4 IV") g4IV("G4 IV"),
        @Json(name = "F3 VI") f3VI("F3 VI"),
        @Json(name = "K4 IV") k4IV("K4 IV"),
        @Json(name = "G5 IV") g5IV("G5 IV"),
        @Json(name = "G3 IV") g3IV("G3 IV"),
        @Json(name = "G1 IV") g1IV("G1 IV"),
        @Json(name = "K7 IV") k7IV("K7 IV"),
        @Json(name = "G0 IV") g0IV("G0 IV"),
        @Json(name = "K6 IV") k6IV("K6 IV"),
        @Json(name = "K9 IV") k9IV("K9 IV"),
        @Json(name = "G2 IV") g2IV("G2 IV"),
        @Json(name = "F9 IV") f9IV("F9 IV"),
        @Json(name = "F0 IV") f0IV("F0 IV"),
        @Json(name = "K8 IV") k8IV("K8 IV"),
        @Json(name = "G8 IV") g8IV("G8 IV"),
        @Json(name = "F6 IV") f6IV("F6 IV"),
        @Json(name = "F5 IV") f5IV("F5 IV"),
        @Json(name = "A0") a0("A0"),
        @Json(name = "A0IV") a0IV("A0IV"),
        @Json(name = "A0IV2") a0IV2("A0IV2");
    }
}

