/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param categoryId category_id integer
 * @param groups groups array
 * @param name name string
 * @param published published boolean
 */

data class GetUniverseCategoriesCategoryIdOk (
    /* category_id integer */
    @Json(name = "category_id")
    var categoryId: kotlin.Int,
    /* groups array */
    @Json(name = "groups")
    var groups: kotlin.Array<kotlin.Int>,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    /* published boolean */
    @Json(name = "published")
    var published: kotlin.Boolean
)

