/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models

import tv.z85.esi.models.GetUniverseMoonsMoonIdPosition

import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param moonId moon_id integer
 * @param name name string
 * @param position 
 * @param systemId The solar system this moon is in
 */

data class GetUniverseMoonsMoonIdOk (
    /* moon_id integer */
    @Json(name = "moon_id")
    var moonId: kotlin.Int,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    @Json(name = "position")
    var position: GetUniverseMoonsMoonIdPosition,
    /* The solar system this moon is in */
    @Json(name = "system_id")
    var systemId: kotlin.Int
)

