/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param cycleTime Time in seconds to process a run
 * @param schematicName schematic_name string
 */

data class GetUniverseSchematicsSchematicIdOk (
    /* Time in seconds to process a run */
    @Json(name = "cycle_time")
    var cycleTime: kotlin.Int,
    /* schematic_name string */
    @Json(name = "schematic_name")
    var schematicName: kotlin.String
)

