/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * dogma_effect object
 * @param effectId effect_id integer
 * @param isDefault is_default boolean
 */

data class GetUniverseTypesTypeIdDogmaEffect (
    /* effect_id integer */
    @Json(name = "effect_id")
    var effectId: kotlin.Int,
    /* is_default boolean */
    @Json(name = "is_default")
    var isDefault: kotlin.Boolean
)

