/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * 200 ok object
 * @param constellations constellations array
 * @param description description string
 * @param name name string
 * @param regionId region_id integer
 */

data class GetUniverseRegionsRegionIdOk (
    /* constellations array */
    @Json(name = "constellations")
    var constellations: kotlin.Array<kotlin.Int>,
    /* description string */
    @Json(name = "description")
    var description: kotlin.String? = null,
    /* name string */
    @Json(name = "name")
    var name: kotlin.String,
    /* region_id integer */
    @Json(name = "region_id")
    var regionId: kotlin.Int
)

