/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * The aggressor corporation or alliance that declared this war, only contains either corporation_id or alliance_id
 * @param allianceId Alliance ID if and only if the aggressor is an alliance
 * @param corporationId Corporation ID if and only if the aggressor is a corporation
 * @param iskDestroyed ISK value of ships the aggressor has destroyed
 * @param shipsKilled The number of ships the aggressor has killed
 */

data class GetWarsWarIdAggressor (
    /* Alliance ID if and only if the aggressor is an alliance */
    @Json(name = "alliance_id")
    var allianceId: kotlin.Int? = null,
    /* Corporation ID if and only if the aggressor is a corporation */
    @Json(name = "corporation_id")
    var corporationId: kotlin.Int? = null,
    /* ISK value of ships the aggressor has destroyed */
    @Json(name = "isk_destroyed")
    var iskDestroyed: kotlin.Float,
    /* The number of ships the aggressor has killed */
    @Json(name = "ships_killed")
    var shipsKilled: kotlin.Int
)

