/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * item object
 * @param flag Fitting location for the item. Entries placed in 'Invalid' will be discarded. If this leaves the fitting with nothing, it will cause an error.
 * @param quantity quantity integer
 * @param typeId type_id integer
 */

data class PostCharactersCharacterIdFittingsItem (
    /* Fitting location for the item. Entries placed in 'Invalid' will be discarded. If this leaves the fitting with nothing, it will cause an error. */
    @Json(name = "flag")
    var flag: PostCharactersCharacterIdFittingsItem.Flag,
    /* quantity integer */
    @Json(name = "quantity")
    var quantity: kotlin.Int,
    /* type_id integer */
    @Json(name = "type_id")
    var typeId: kotlin.Int
) {

    /**
    * Fitting location for the item. Entries placed in 'Invalid' will be discarded. If this leaves the fitting with nothing, it will cause an error.
    * Values: cargo,droneBay,fighterBay,hiSlot0,hiSlot1,hiSlot2,hiSlot3,hiSlot4,hiSlot5,hiSlot6,hiSlot7,invalid,loSlot0,loSlot1,loSlot2,loSlot3,loSlot4,loSlot5,loSlot6,loSlot7,medSlot0,medSlot1,medSlot2,medSlot3,medSlot4,medSlot5,medSlot6,medSlot7,rigSlot0,rigSlot1,rigSlot2,serviceSlot0,serviceSlot1,serviceSlot2,serviceSlot3,serviceSlot4,serviceSlot5,serviceSlot6,serviceSlot7,subSystemSlot0,subSystemSlot1,subSystemSlot2,subSystemSlot3
    */
    
    enum class Flag(val value: kotlin.String){
        @Json(name = "Cargo") cargo("Cargo"),
        @Json(name = "DroneBay") droneBay("DroneBay"),
        @Json(name = "FighterBay") fighterBay("FighterBay"),
        @Json(name = "HiSlot0") hiSlot0("HiSlot0"),
        @Json(name = "HiSlot1") hiSlot1("HiSlot1"),
        @Json(name = "HiSlot2") hiSlot2("HiSlot2"),
        @Json(name = "HiSlot3") hiSlot3("HiSlot3"),
        @Json(name = "HiSlot4") hiSlot4("HiSlot4"),
        @Json(name = "HiSlot5") hiSlot5("HiSlot5"),
        @Json(name = "HiSlot6") hiSlot6("HiSlot6"),
        @Json(name = "HiSlot7") hiSlot7("HiSlot7"),
        @Json(name = "Invalid") invalid("Invalid"),
        @Json(name = "LoSlot0") loSlot0("LoSlot0"),
        @Json(name = "LoSlot1") loSlot1("LoSlot1"),
        @Json(name = "LoSlot2") loSlot2("LoSlot2"),
        @Json(name = "LoSlot3") loSlot3("LoSlot3"),
        @Json(name = "LoSlot4") loSlot4("LoSlot4"),
        @Json(name = "LoSlot5") loSlot5("LoSlot5"),
        @Json(name = "LoSlot6") loSlot6("LoSlot6"),
        @Json(name = "LoSlot7") loSlot7("LoSlot7"),
        @Json(name = "MedSlot0") medSlot0("MedSlot0"),
        @Json(name = "MedSlot1") medSlot1("MedSlot1"),
        @Json(name = "MedSlot2") medSlot2("MedSlot2"),
        @Json(name = "MedSlot3") medSlot3("MedSlot3"),
        @Json(name = "MedSlot4") medSlot4("MedSlot4"),
        @Json(name = "MedSlot5") medSlot5("MedSlot5"),
        @Json(name = "MedSlot6") medSlot6("MedSlot6"),
        @Json(name = "MedSlot7") medSlot7("MedSlot7"),
        @Json(name = "RigSlot0") rigSlot0("RigSlot0"),
        @Json(name = "RigSlot1") rigSlot1("RigSlot1"),
        @Json(name = "RigSlot2") rigSlot2("RigSlot2"),
        @Json(name = "ServiceSlot0") serviceSlot0("ServiceSlot0"),
        @Json(name = "ServiceSlot1") serviceSlot1("ServiceSlot1"),
        @Json(name = "ServiceSlot2") serviceSlot2("ServiceSlot2"),
        @Json(name = "ServiceSlot3") serviceSlot3("ServiceSlot3"),
        @Json(name = "ServiceSlot4") serviceSlot4("ServiceSlot4"),
        @Json(name = "ServiceSlot5") serviceSlot5("ServiceSlot5"),
        @Json(name = "ServiceSlot6") serviceSlot6("ServiceSlot6"),
        @Json(name = "ServiceSlot7") serviceSlot7("ServiceSlot7"),
        @Json(name = "SubSystemSlot0") subSystemSlot0("SubSystemSlot0"),
        @Json(name = "SubSystemSlot1") subSystemSlot1("SubSystemSlot1"),
        @Json(name = "SubSystemSlot2") subSystemSlot2("SubSystemSlot2"),
        @Json(name = "SubSystemSlot3") subSystemSlot3("SubSystemSlot3");
    }
}

