/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * invitation object
 * @param characterId The character you want to invite
 * @param role If a character is invited with the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is invited with the `wing_commander` role, only `wing_id` should be specified. If a character is invited with the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is invited with the `squad_member` role, `wing_id` and `squad_id` should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.
 * @param squadId squad_id integer
 * @param wingId wing_id integer
 */

data class PostFleetsFleetIdMembersInvitation (
    /* The character you want to invite */
    @Json(name = "character_id")
    var characterId: kotlin.Int,
    /* If a character is invited with the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is invited with the `wing_commander` role, only `wing_id` should be specified. If a character is invited with the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is invited with the `squad_member` role, `wing_id` and `squad_id` should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions. */
    @Json(name = "role")
    var role: PostFleetsFleetIdMembersInvitation.Role,
    /* squad_id integer */
    @Json(name = "squad_id")
    var squadId: kotlin.Long? = null,
    /* wing_id integer */
    @Json(name = "wing_id")
    var wingId: kotlin.Long? = null
) {

    /**
    * If a character is invited with the `fleet_commander` role, neither `wing_id` or `squad_id` should be specified. If a character is invited with the `wing_commander` role, only `wing_id` should be specified. If a character is invited with the `squad_commander` role, both `wing_id` and `squad_id` should be specified. If a character is invited with the `squad_member` role, `wing_id` and `squad_id` should either both be specified or not specified at all. If they aren’t specified, the invited character will join any squad with available positions.
    * Values: fleetCommander,wingCommander,squadCommander,squadMember
    */
    
    enum class Role(val value: kotlin.String){
        @Json(name = "fleet_commander") fleetCommander("fleet_commander"),
        @Json(name = "wing_commander") wingCommander("wing_commander"),
        @Json(name = "squad_commander") squadCommander("squad_commander"),
        @Json(name = "squad_member") squadMember("squad_member");
    }
}

