/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * contents object
 * @param labels Labels to assign to the mail. Pre-existing labels are unassigned.
 * @param read Whether the mail is flagged as read
 */

data class PutCharactersCharacterIdMailMailIdContents (
    /* Labels to assign to the mail. Pre-existing labels are unassigned. */
    @Json(name = "labels")
    var labels: kotlin.Array<kotlin.Int>? = null,
    /* Whether the mail is flagged as read */
    @Json(name = "read")
    var read: kotlin.Boolean? = null
)

