/**
* EVE Swagger Interface
* An OpenAPI for EVE Online
*
* The version of the OpenAPI document: 1.7.2
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package tv.z85.esi.models


import com.squareup.moshi.Json
/**
 * new_settings object
 * @param isFreeMove Should free-move be enabled in the fleet
 * @param motd New fleet MOTD in CCP flavoured HTML
 */

data class PutFleetsFleetIdNewSettings (
    /* Should free-move be enabled in the fleet */
    @Json(name = "is_free_move")
    var isFreeMove: kotlin.Boolean? = null,
    /* New fleet MOTD in CCP flavoured HTML */
    @Json(name = "motd")
    var motd: kotlin.String? = null
)

